conf.py:
  copyright: 2017, Thomas Hucke
  project: Timezones
  version: 2.0
  release: 2.0
  html_theme_options:
    github_repository: thucke/TYPO3.ext.timezones
    github_branch: master
  latex_documents:
  - - Index
    - timezones.tex
    - Manages timezones in your website
    - Thomas Hucke
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}