name: acceptance tests

on:
  workflow_dispatch:

jobs:
  acceptance-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set PHP version
      - name: Set PHP version
        run: |
            sed -i -e 's/^php_version:.*/php_version: ${{ matrix.env.php }}/g' .ddev/config.yaml
      # Start ddev
      - name: Init DDEV
        uses: jonaseberle/github-action-setup-ddev@v1
      # Setup tests
      - name: Setup Tests
        run: ddev composer cookieman:${{ matrix.theme }}
      # Run tests
      - name: Run tests
        run: ddev composer thucke:test:php:acceptance

      # Save acceptance reports
      - name: Upload Codeception output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.browser }}-${{ matrix.theme }}-${{ matrix.php-version }}-ar
          path: .Build/var/acceptance

      - name: Upload PHP log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: php-log
          path: php.log.txt
