name: acceptance tests

on:
  workflow_dispatch:

jobs:
  acceptance-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env:
          - { php: 7.4, TYPO3_VERSION: ^10.4, TESTING_FRAMEWORK: ^6.5.0 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set PHP version
      - name: Set PHP version
        run: |
            sed -i -e 's/^php_version:.*/php_version: ${{ matrix.env.php }}/g' .ddev/config.yaml
      # Start ddev
      - name: Init DDEV
        uses: jonaseberle/github-action-setup-ddev@v1
      # Setup tests
      - name: Setup Tests
        run: ddev composer install --dev typo3/testing-framework="${TESTING_FRAMEWORK}" typo3/cms-core="${TYPO3_VERSION}"
      # Run tests
      - name: Run tests
        run: ddev composer thucke:test:php:acceptance

      # Save acceptance reports
      - name: Upload Codeception output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: codeception-results--${{ matrix.env.php }}
          path: .Build/var/acceptance

      - name: Upload PHP log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: php-log
          path: php.log.txt
