name: acceptance tests

on:
  workflow_dispatch:

jobs:
  acceptance-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env:
          - { php: 7.4, TYPO3_VERSION: ^10.4, TESTING_FRAMEWORK: ^6.5.0 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set PHP version
      - name: Set PHP version
        run: |
            sed -i -e 's/^php_version:.*/php_version: ${{ matrix.env.php }}/g' .ddev/config.yaml
      # Start ddev
      - name: Init DDEV
        uses: jonaseberle/github-action-setup-ddev@master

      # Setup tests
      - name: Setup Tests
        env:
          TYPO3_VERSION: ${{ matrix.env.TYPO3_VERSION }}
          TESTING_FRAMEWORK: ${{ matrix.env.TESTING_FRAMEWORK }}
          TYPO3_CONTEXT: Development
          typo3DatabaseName: t3acceptance
        run: |
          ddev composer require typo3/testing-framework="${TESTING_FRAMEWORK}" typo3/cms-core="${TYPO3_VERSION}"
          ddev mysql --host="127.0.0.1" --user="root" --password="root" < Tests/Acceptance/_data/dbcreate_${typo3DatabaseName}.sql
          ddev mysql --host="127.0.0.1" --user="root" --password="root" < Tests/Acceptance/_data/t3acceptance_${TYPO3_VERSION}.sql

      # Run tests
      - name: Run tests
        env:
          CODECEPTION_ENV: github-actions
          TYPO3_VERSION: ${{ matrix.env.TYPO3_VERSION }}
          IS_T3ACCEPTANCE_RUN: true
          TYPO3_CONTEXT: Development
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
          typo3DatabaseName: t3acceptance
        run: ddev composer thucke:test:php:acceptance

      # Save acceptance reports
      - name: Upload Codeception output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: codeception-results-${{ matrix.env.php }}
          path: .Build/var/acceptance

      - name: Upload PHP log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: php-log
          path: php.log.txt
