name: acceptance tests

on:
  workflow_dispatch:

jobs:
  acceptance-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env:
          - { php: 7.4, TYPO3_VERSION: ^10.4, TESTING_FRAMEWORK: ^6.16.2 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.env.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
          tools: composer:v2, php-cs-fixer
          extension: pdo, sqlite3

      # composer
      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version
          php --version
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Ensure stability dev
        if: ${{ matrix.env.TYPO3_VERSION == 'dev-main' }}
        run: |
          composer config minimum-stability dev
          composer config prefer-stable true
      - name: Install TYPO3 core
        env:
          TYPO3_VERSION: ${{ matrix.env.TYPO3_VERSION }}
          TESTING_FRAMEWORK: ${{ matrix.env.TESTING_FRAMEWORK }}
        run: |
          composer require --dev typo3/testing-framework="${TESTING_FRAMEWORK}" typo3/cms-core="${TYPO3_VERSION}"
          cp -R Tests/Acceptance/_data/typo3conf .Build/public/
          cp -R Tests/Acceptance/_data/config .Build/
          [ ${TYPO3_VERSION} != "^11.5" ] && .Build/bin/typo3cms install:generatepackagestates

      - name: Start database server
        run: sudo /etc/init.d/mysql start

      - name: Run PHP webserver
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          sed -i -e "s/LOCAL_DOMAIN/$APP_IP:8888/" Tests/Acceptance/_envs/github-actions.yml
          php -S 0.0.0.0:8888 -t .Build/public/ &> php.log.txt &
          sleep 2;
      - name: Test PHP webserver and initialize TYPO3 cache
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          curl "$APP_IP:8888"

      - name: Start Selenium standalone
        run: |
          echo $SELENIUM_JAR_PATH
          java -Djava.awt.headless=true -jar $SELENIUM_JAR_PATH standalone &
          sleep 3;
      - name: Acceptance Tests
        env:
          CODECEPTION_ENV: github-actions
          TYPO3_VERSION: ${{ matrix.env.TYPO3_VERSION }}
          IS_T3ACCEPTANCE_RUN: true
          TYPO3_CONTEXT: Development
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
          typo3DatabaseName: t3acceptance
        run: |
          cp -R Tests/Acceptance/_data/typo3conf .Build/public/
          cp -R Tests/Acceptance/_data/config .Build/
          .Build/bin/typo3cms install:generatepackagestates
          codecept run acceptance --env=${CODECEPTION_ENV} -d -c Tests/Build/AcceptanceTests.yml --html
          
      # Save acceptance reports
      - name: Upload Codeception output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: codeception-results-${{ matrix.env.php }}
          path: .Build/var/acceptance

      - name: Upload PHP log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: php-log
          path: php.log.txt
