name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # mysql-service Label used to access the service container
      mysql-service:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          ## Accessing to Github secrets, where you can store your configuration
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: t3func
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        typo3: [ ^9.5, ^10.4 ]
        php: [ '7.4' ]
        include:
          - typo3: ^10.4
            php: '7.4'
            coverage: true
          - typo3: ^10.4
            php: '7.3'
          - typo3: ^9.5
            php: '7.4'
          - typo3: ^9.5
            php: '7.3'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, php-cs-fixer

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      - name: Info
        run: composer info

      - name: CGL
        run: composer thucke:cgl

      - name: PHPStan Classes
        if: matrix.php > '7.2'
        run: composer thucke:phpstan:classes

      - name: Lint PHP
        run: composer thucke:test:php:lint

      - name: Unit Tests without coverage
        run: composer thucke:test:php:unit

      - name: Functional Tests without coverage
        run: composer thucke:test:php:functional
        env:
          typo3DatabaseHost: mysql-service
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
          typo3DatabasePort: 33306
          TYPO3_CONEXT: Development
